# Generated by Django 3.2.13 on 2024-08-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
