# Generated by Django 3.2.13 on 2024-08-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_book_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cost',
        ),
    ]
