# Generated by Django 3.2.13 on 2024-08-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_book_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='release_year',
        ),
    ]
