# Generated by Django 3.2.13 on 2024-08-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_book_release_year'),
    ]

    operations = [
    ]
